### ISSUE TITLE
Log Wording Ambiguous

### ISSUE THREAD

**Issue by DarioS** [Ensembl/Bio-DB-HTS#91] opened 2020-03-26 00:00 UTC
I get an error such as

```
Configuring Bio-DB-HTS-3.01 ... N/A
! Configure failed for Bio-DB-HTS-3.01. See /users/stgrad/dario/.cpanm/work/1585179865.8235/build.log for details.
```

I use `cpanm` to install it. When I look at the log file it's not clear what the error is

```
Running Build.PL

This module requires HTSlib (http://htslib.org/)
Install it if you have not done so already.

This script will attempt to locate HTSlib by looking for htslib/hts.h
and libhts.a / libhts.so in:

  1. --htslib command line argument
  2. HTSLIB_DIR environment variable
  3. --prefix command line argument (which also sets installation location)
  4. Alien::HTSlib dependency resolver
  5. pkg-config (extra directories can be set in PKG_CONFIG_PATH environment variable)
  6. common library locations: /usr /usr/local, /usr/share, /opt/local

-> N/A
-> FAIL Configure failed for Bio-DB-HTS-3.01. See /users/stgrad/dario/.cpanm/work/1585179865.8235/build.log for details.
```

"This script will attempt to locate HTSlib ..." doesn't explain whether the script successfully found HTSlib or not for my particular instance. Also, the end of the log file advises "See /users/stgrad/dario/.cpanm/work/1585179865.8235/build.log for details." But, I am already viewing that file, so the user should not be instructed to re-open the log file they already opened.

I'm baffled why this script can't detect HTSlib on the server I'm using:

```
~$ dpkg --list | grep hts
ii  libhts-dev:amd64    1.9-11    amd64    development files for the HTSlib
ii  libhts2:amd64    1.9-11    amd64    C library for high-throughput sequencing data formats
ii  python-htseq    0.11.2-1    amd64    Python high-throughput genome sequencing read analysis utilities
```

**Comment by dboehmer** [comment] 2021-12-21 20:35
I have the same Issue on the recent Debian Bullseye (11).

```console
$ dpkg --list | grep hts
ii  libhts-dev:amd64                              1.11-4                          amd64        development files for the HTSlib
ii  libhts3:amd64                                 1.11-4                          amd64        C library for high-throughput sequencing data formats
$ find /usr/ -name hts.h -or -name libhts.so
/usr/lib/x86_64-linux-gnu/libhts.so
/usr/include/htslib/hts.h
```

I tried these without success:

* `HTSLIB_DIR=/usr/lib/x86_64-linux-gnu/ cpanm -v Bio::DB::HTS`
* `HTSLIB_DIR=/usr/include/htslib/ cpanm -v Bio::DB::HTS`
* `PKG_CONFIG_PATH=/usr/include/htslib/:/usr/lib/x86_64-linux-gnu/ cpanm -v Bio::DB::HTS`

The log message `See .../build.log for details` comes from cpan/cpanm, I think, and is not specific to this CPAN distribution.

@DarioS Could you install this dist eventually? If so, how?

**Comment by sgiorgetti** [comment] 2021-12-22 21:32
@dboehmer I could reproduce the error on Ubuntu 21.10 (Impish Indri), using HTSLIB_DIR as per your message above.
I did not find a way around it.

However, I can give you 2 ways to install Bio-DB-HTS.

**Pre-compiled libraries - somewhat easier**
- Install both the library and the header/development files for htslib: in the Debian world names should be _libhts3_ and _libhts-dev_
- Locate the files _libhts.so_ and _hts.h_: your cmd line above works perfectly
- Clone Bio-DB-HTS repo and switch to the desired branch (I used the default one)
- In Bio-DB-HTS run
`perl Build.PL --htslib-includedir /usr/include/htslib --htslib-libdir /lib/x86_64-linux-gnu`
- And after that
`./Build`

**htslib Git repo - less easy one**
- Clone and compile htslib (make sure to install all the required dependencies)
```
$ git clone --branch master --depth 1 https://github.com/samtools/htslib.git
$ cd htslib
$ make
$ export HTSLIB_DIR=<some root dir>/htslib/
```
- You may want to add HTSLIB_DIR to your _.bashrc_ or _.profile_
- Clone Bio-DB-HTS repo and run `perl Build.PL` and `./Build`

**Final comments**
- To compile, I used standard _gcc version 11.2.0_
- The `perl Build.PL` worked fine, but got some warnings running `./Build`
- Used Perl 5.26.3 (with plenv), because it is supported by Ensembl
- Had to work a bit my way through Perl modules installation because of missing some required system libraries - e.g. libexpat, liblzma

**Comment by sgiorgetti** [comment] 2024-09-19 11:56
Closing because of aging. Please, re-open this if you feel it's still current

**Closed as completed by sgiorgetti** 2024-09-19 11:56 UTC
